### ISSUE TITLE
Doesn't generate resized image

### ISSUE THREAD

**Issue by dud3** [spescina/imgproxy#5]
File/Folder: `$img = avatars/avatar_xy/xa9DAfeX.png`

For some reason after I give the img. path to the method: `ImgProxy::link($img, 200, 200)` I get the URL, but there's no resized picture on the public folder ?

Generated URL:
http://localhost:8000/packages/spescina/imgproxy/200/200/1/90/avatars/avatar_xy/xa9DAfeX.png

What could be the problem ?

**Comment by spescina** [comment]
Generated images are stored in the app/storage/cache/imgproxy folder. I don't understand if your problem is that the generated url does not load the image or if you don't find the image file in the public folder.

**Comment by dud3** [comment]
Can't find the image on public folder.

**Comment by spescina** [comment]
as stated before, there's no image in the public folder... temp images are stored in the app/storage/cache/imgproxy folder but the app will show the cached image if you call the generated url. google for timthumb for understanding it's behaviour.

**Comment by dud3** [comment]
For some reason there's no folder called `/imgproxy` on `app/storage/cache/`, and I'm pretty sure that folder has `+rwx` permission set.

**Comment by spescina** [comment]
do you see the image when opening the generated url in the browser?

**Comment by dud3** [comment]
I was jut trying it over and over again but unfortunately not.

**Comment by dud3** [comment]
Actually on the remote server I get the URL like:
http://dev2.mymxlog.com/packages/spescina/imgproxy/100/100/1/90/home/ubuntu/dev2.mymxlog.com/public/avatars/demo@gmail.com/TRchD9R2.png

But it's like there's an empty/default picture in it(check the link above) ?

**Comment by dud3** [comment]
And BTW on the remote server there's the `/imgproxy` folder also.

**Comment by spescina** [comment]
there's something weird. I don't understand why you have this url...
the correct url is this http://dev2.mymxlog.com/packages/spescina/imgproxy/100/100/1/90/avatars/demo@gmail.com/TRchD9R2.png and in fact it works. try to figure out why there's the full system path in the url

**Comment by dud3** [comment]
Alright that solved it, the whole problem was on full system path, it seems that I was giving it the full system path.
Everything works fine.

Thanks a lot.

<i>You might close this issue.</i>

**Comment by spescina** [comment]
ok
